---
- hosts: consul
  # Prevent error occurs before pre_tasks. (ex. Docker container isn't running.)
  gather_facts: no
  pre_tasks:
    - set_fact:
        utility_module_path: "{{ utility_module_path|default('../../ansible_utility') }}"
    - name: Do pre-task for each platform
      include: "{{ utility_module_path }}/pre_tasks/{{ ansible_connection }}.yml"
    - name: "Gather fact information on target platform."
      setup:
  roles:
    - role: FGtatsuro.consul
  tasks:
    - block:
      - name: Ensure /opt/consul directory exists
        file:
          path: '/opt/consul'
          owner: 'root'
          group: 'root'
          state: 'directory'
      # TODO: Create custom role to put these settings.
      - name: Set service script
        template:
          src: '../resources/consul/services.sh'
          dest: '/opt/consul/services.sh'
          mode: '0755'
      become: yes
  post_tasks:
    - name: Do post-task for each platform
      include: "{{ utility_module_path }}/post_tasks/{{ ansible_connection }}.yml"
- hosts: nomad
  # Prevent error occurs before pre_tasks. (ex. Docker container isn't running.)
  gather_facts: no
  pre_tasks:
    - set_fact:
        utility_module_path: "{{ utility_module_path|default('../../ansible_utility') }}"
    - name: Do pre-task for each platform
      include: "{{ utility_module_path }}/pre_tasks/{{ ansible_connection }}.yml"
    - name: "Gather fact information on target platform."
      setup:
  roles:
    - role: FGtatsuro.nomad
  tasks:
    - block:
      - name: Ensure /opt/nomad directory exists
        file:
          path: '/opt/nomad'
          owner: 'root'
          group: 'root'
          state: 'directory'
      # TODO: Create custom role to put these settings.
      - name: Set service script
        template:
          src: '../resources/nomad/services.sh'
          dest: '/opt/nomad/services.sh'
          mode: '0755'
      become: yes
  post_tasks:
    - name: Do post-task for each platform
      include: "{{ utility_module_path }}/post_tasks/{{ ansible_connection }}.yml"
